### ISSUE TITLE
Add support for issues

### ISSUE THREAD

**Issue by beep-boop-remo** [JulienKode/team-labeler-action#125]
This action only works with Pull Requests. It is not able to label issues based on author. It just fails silently without adding label.

![image](https://user-images.githubusercontent.com/81965134/134897811-3e2da505-5314-4dbd-9fee-66f45ba5b339.png)

**Comment by JulienKode** [comment]
Hi @boris-remo 

Thanks for this idea, you right we can implement this for issue too

**Comment by JulienKode** [comment]
This action now supports issues https://github.com/JulienKode/team-labeler-action/releases/tag/v1.1.0
