### ISSUE TITLE
What `GITHUB_TOKEN` permission are needed?

### ISSUE THREAD

**Issue by nick-at-work** [JulienKode/team-labeler-action#155]
If you could list the permissions needed on the `GITHUB_TOKEN`, it might save some time for others who run into the same issue that I did. Our `GITHUB_TOKEN` permissions are set org-wide to read-only, so we have to override in each workflow file. This is what I used:

```yaml
permissions:
  content: read
  pull_requests: write
```

However it looks like if the label doesn't exist, it might need more write permissions to create it (See: #88). Unfortunately the GitHub docs aren't that detailed about what permissions allow you to do what, as far as I can tell.

**Comment by JulienKode** [comment]
Thanks for the informations @nick-at-work

**Comment by JulienKode** [comment]
@toadjaune added it to the readme in #184 so I close this 

Feel free to reopen it if you still have this issue
