### ISSUE TITLE
Feature Request: return labels as output

### ISSUE THREAD

**Issue by mariaines** [JulienKode/team-labeler-action#194]
Hi @JulienKode, thanks for this action! I'd love the ability to get the discovered labels as output. Are you open to pull requests? I think it shouldn't be too hard...

**Comment by JulienKode** [comment]
@mariaines 

Thanks for this suggestion and the PR, that's perfect 

I'll review it and merge it

**Comment by JulienKode** [comment]
Thanks for your contribution, I've merged https://github.com/JulienKode/team-labeler-action/pull/195
