### ISSUE TITLE
Compare usernames without case-senstitivity

### ISSUE THREAD

**Issue by AntonNiklasson** [JulienKode/team-labeler-action#200]
It seems like the username matching is case-sensitive. It would be convenient to not have that, since it just silently "fails".

I'd be happy to help out, I just don't have time right now.

**Comment by JulienKode** [comment]
Hi @AntonNiklasson 

Thanks to @7PH who did this PR: https://github.com/JulienKode/team-labeler-action/pull/216

**Comment by 7PH** [comment]
Hey @JulienKode , thanks again for merging, do you plan on releasing a new version in the next weeks?

**Comment by 7PH** [comment]
I'm pinging you again @JulienKode because last time you said you missed my notification, don't feel rushed if you don't have time to make a release though 😉 Also please do not hesitate to let me know if I can help

**Comment by 7PH** [comment]
Hello, here's your monthly ping @JulienKode 😁

**Comment by 7PH** [comment]
Monthly ping again @JulienKode 🤗 do you plan to release at some point?

**Comment by AntonNiklasson** [comment]
You can specify a commit as the version. Perhaps that unblocks you a bit.

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions

**Comment by 7PH** [comment]
> You can specify a commit as the version. Perhaps that unblocks you a bit.
> 
> https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions

Hey @AntonNiklasson , thanks for the tip! That's for the company, so I can't really point to a specific commit as using a proper released version is a cleaner solution for us

**Comment by JulienKode** [comment]
@7PH @AntonNiklasson I am really sorry to take so much time to respond, thanks for all of your help

@7PH thanks for adding this feature I've released it today in https://github.com/JulienKode/team-labeler-action/releases/tag/v1.2.0
